// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQj8Fm2MkJBfGS7xOer603n4PEEFrz5vI',
    appId: '1:320954302799:web:5de205c3ae82fc8bcc053a',
    messagingSenderId: '320954302799',
    projectId: 'fir-basic-app-55466',
    authDomain: 'fir-basic-app-55466.firebaseapp.com',
    storageBucket: 'fir-basic-app-55466.firebasestorage.app',
    measurementId: 'G-YWPCQEND9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCtEXn6lTipKLFAHsSvEy-PKOdzkd6UZA',
    appId: '1:320954302799:android:c925a0af6dda3700cc053a',
    messagingSenderId: '320954302799',
    projectId: 'fir-basic-app-55466',
    storageBucket: 'fir-basic-app-55466.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6efjV5IUYYEsLT6d8gHf7aPUCQUb_dsQ',
    appId: '1:320954302799:ios:4e73958632e23cc3cc053a',
    messagingSenderId: '320954302799',
    projectId: 'fir-basic-app-55466',
    storageBucket: 'fir-basic-app-55466.firebasestorage.app',
    iosBundleId: 'com.example.firebaseBasicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6efjV5IUYYEsLT6d8gHf7aPUCQUb_dsQ',
    appId: '1:320954302799:ios:4e73958632e23cc3cc053a',
    messagingSenderId: '320954302799',
    projectId: 'fir-basic-app-55466',
    storageBucket: 'fir-basic-app-55466.firebasestorage.app',
    iosBundleId: 'com.example.firebaseBasicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQj8Fm2MkJBfGS7xOer603n4PEEFrz5vI',
    appId: '1:320954302799:web:18645b020edd3170cc053a',
    messagingSenderId: '320954302799',
    projectId: 'fir-basic-app-55466',
    authDomain: 'fir-basic-app-55466.firebaseapp.com',
    storageBucket: 'fir-basic-app-55466.firebasestorage.app',
    measurementId: 'G-V897936S7V',
  );
}
